USE developer;

CREATE TABLE WEBBUILD(

S_ID INT PRIMARY KEY,
S_NAME VARCHAR(100),
S_SALARY DECIMAL(10,2),
S_DEPARTMENT VARCHAR(50)


);


DESC WEBBUILD;

INSERT INTO WEBBUILD VALUE
('724','ABUL','50000','FRONT-END-DEV'),
('723','SAAD','60000','BACK-END-DEV'),
('725','FAIZ','80000','SENIOR-DEVELOPER'),
('726','SHAIF','90000','JUNIOR-DEVELOPER'),
('727','ZAID','55000','APPS-DEVELOPER');

SELECT * FROM WEBBUILD;

SELECT COUNT(S_ID) AS TOTAL_STAFF
FROM WEBBUILD;

SELECT SUM(S_SALARY) AS TOTAL_SALARY
FROM WEBBUILD;

SELECT AVG(S_SALARY) AS AVERAGE_SALARY
FROM WEBBUILD;

SELECT MIN(S_SALARY) AS MINIMUM_SALARY
FROM WEBBUILD;

SELECT  MAX(S_SALARY) AS MAXIMUM_SALARY
FROM WEBBUILD;


SELECT S_DEPARTMENT, AVG(S_SALARY) AS AVERAGE_SALARY
FROM WEBBUILD
GROUP BY S_DEPARTMENT
HAVING AVG(S_SALARY) > 50000;

SELECT COUNT(S_ID) AS TOTAL_STAFF,
       AVG(S_SALARY) AS AVERAGE_SALARY,
       MAX(S_SALARY) AS MAXIMUM_SALARY,
       MIN(S_SALARY) AS MINIMUM_SALARY,
       SUM(S_SALARY) AS TOTAL_SALARY
FROM WEBBUILD;





